import { toJson } from "./files";
import { buildSetupPlan } from "./setup";
import type {
	CreateContext,
	GeneratedFile,
	GeneratedProject,
	RecipeId,
	RecipeManifest,
	RecipeLock,
} from "./types";

const pins = {
	vitePlus: "0.2.1",
	vite: "8.0.16",
	viteReact: "6.0.2",
	typescript: "6.0.3",
	react: "19.2.7",
	reactDom: "19.2.7",
	typesReact: "19.2.17",
	typesReactDom: "19.2.3",
	typesNode: "26.0.0",
	convex: "1.41.0",
	convexWorkos: "0.0.3",
	workosAuthKitReact: "0.16.1",
	shadcn: "4.11.0",
	tailwindcss: "4.3.1",
	tailwindcssVite: "4.3.1",
	vitest: "4.1.9",
	lucideReact: "1.21.0",
	classVarianceAuthority: "0.7.1",
	clsx: "2.1.1",
	tailwindMerge: "3.6.0",
	radixUi: "1.6.0",
	concurrently: "10.0.3",
	prettier: "3.8.4",
	eslint: "10.5.0",
} as const;

const lockDate = "2026-06-22";

function file(path: string, contents: string): GeneratedFile {
	return { path, contents: `${contents.trim()}\n` };
}

function lock(recipe: RecipeId, notes: string[]): RecipeLock {
	return {
		version: 1,
		recipe,
		updatedAt: lockDate,
		pins,
		notes,
	};
}

function rootReadme(ctx: CreateContext, title: string): GeneratedFile {
	return file(
		"README.md",
		`# ${title}

Generated by create-m10n.

## Quick Start

\`\`\`bash
${ctx.packageManager} install
${ctx.packageManager === "bun" ? "bunx" : "npx"} convex dev
${ctx.packageManager} run dev
\`\`\`

## Agent Contract

Before editing Convex functions, run:

\`\`\`bash
${ctx.packageManager === "bun" ? "bunx" : "npx"} convex ai-files install
\`\`\`

Then read \`convex/_generated/ai/guidelines.md\` and \`AGENTS.md\`.
`,
	);
}

function agentInstructions(ctx: CreateContext): GeneratedFile {
	return file(
		"AGENTS.md",
		`# Agent Instructions

This project is an agent-native scaffold. Optimize changes for small, verified feature slices.

## Required First Steps

- Read \`docs/architecture.md\` before changing app structure.
- Run \`${ctx.packageManager === "bun" ? "bunx" : "npx"} convex ai-files install\` before writing Convex backend code.
- Read \`convex/_generated/ai/guidelines.md\` after Convex generates it.
- Keep shared UI in \`packages/ui\`; do not duplicate base components across apps.
- Keep marketing in \`apps/marketing\` and product surfaces in \`apps/web\`.

## Feature Workflow

1. Define the user-facing workflow in \`docs/feature-workflow.md\`.
2. Add or adjust Convex schema/functions.
3. Wire the product UI in \`apps/web\`.
4. Reuse shared shadcn-style components from \`packages/ui\`.
5. Run \`${ctx.packageManager} run check\`, \`${ctx.packageManager} run test\`, and the relevant app build.

## Guardrails

- Use WorkOS identity through Convex auth helpers; do not invent local session tables.
- Tenant-sensitive queries must check organization membership.
- Billing is a shell in this scaffold. Do not add live Stripe behavior without creating a focused billing recipe first.
- Mobile is intentionally absent in v1. Add it with a future \`mobile-expo\` recipe so the app contract stays explicit.
`,
	);
}

function commonGitignore(): GeneratedFile {
	return file(
		".gitignore",
		`node_modules
dist
.DS_Store
.env
.env.local
.env.*.local
.vercel
.m10n
.turbo
coverage
convex/_generated
`,
	);
}

function microSaasFiles(ctx: CreateContext): GeneratedFile[] {
	const scope = ctx.packageScope;
	const pkg = ctx.projectSlug;

	return [
		rootReadme(ctx, `${ctx.projectName} micro-SaaS`),
		agentInstructions(ctx),
		commonGitignore(),
		file(
			"package.json",
			toJson({
				name: pkg,
				private: true,
				version: "0.1.0",
				type: "module",
				workspaces: ["apps/*", "packages/*"],
				scripts: {
					dev: "bun run dev:web",
					"dev:all":
						'concurrently -r "bun run dev:web" "bun run dev:marketing" "bun run dev:convex"',
					"dev:web": "bun --cwd apps/web dev",
					"dev:marketing": "bun --cwd apps/marketing dev",
					"dev:convex": "bunx convex dev",
					build:
						"bun run build:ui && bun run build:web && bun run build:marketing",
					"build:ui": "bun --cwd packages/ui build",
					"build:web": "bun --cwd apps/web build",
					"build:marketing": "bun --cwd apps/marketing build",
					check:
						"bun run check:ui && bun run check:web && bun run check:marketing && bunx convex typecheck",
					"check:ui": "bun --cwd packages/ui check",
					"check:web": "bun --cwd apps/web check",
					"check:marketing": "bun --cwd apps/marketing check",
					test: "vitest run",
					"vp:check": "vp check",
					"vp:format": "vp format",
					"vp:lint": "vp lint",
					"convex:dev": "bunx convex dev",
					"convex:deploy": "bunx convex deploy",
				},
				dependencies: {
					"@convex-dev/workos": pins.convexWorkos,
					"@workos-inc/authkit-react": pins.workosAuthKitReact,
					convex: pins.convex,
					"react": pins.react,
					"react-dom": pins.reactDom,
				},
				devDependencies: {
					"@tailwindcss/vite": pins.tailwindcssVite,
					"@types/node": pins.typesNode,
					"@types/react": pins.typesReact,
					"@types/react-dom": pins.typesReactDom,
					"@vitejs/plugin-react": pins.viteReact,
					concurrently: pins.concurrently,
					eslint: pins.eslint,
					prettier: pins.prettier,
					tailwindcss: pins.tailwindcss,
					typescript: pins.typescript,
					vite: pins.vite,
					"vite-plus": pins.vitePlus,
					vitest: pins.vitest,
				},
			}),
		),
		file(
			"recipe.lock.json",
			toJson({
				...microSaasRecipe.lock,
				options: {
					auth: ctx.auth,
					billing: ctx.billing,
					deploy: ctx.deploy,
					packageManager: ctx.packageManager,
					shape: ctx.shape,
				},
			}),
		),
		file(
			"vite.config.ts",
			`import { defineConfig } from "vite-plus";

export default defineConfig({
	lint: {
		plugins: ["typescript"],
		options: {
			typeAware: true,
			typeCheck: true,
		},
		overrides: [
			{
				files: ["apps/**", "packages/ui/**"],
				plugins: ["typescript", "react"],
			},
			{
				files: ["**/*.test.ts", "**/*.test.tsx"],
				plugins: ["typescript", "vitest"],
			},
		],
	},
});
`,
		),
		file(
			"tsconfig.json",
			toJson({
				files: [],
				references: [
					{ path: "./packages/ui" },
					{ path: "./apps/web" },
					{ path: "./apps/marketing" },
				],
			}),
		),
		file(
			".env.example",
			`VITE_CONVEX_URL=
VITE_WORKOS_CLIENT_ID=
VITE_WORKOS_REDIRECT_URI=http://localhost:5173/callback
`,
		),
		file(
			"vercel.json",
			toJson({
				$schema: "https://openapi.vercel.sh/vercel.json",
				installCommand: "bun install",
				buildCommand:
					"bunx convex deploy --cmd-url-env-var-name VITE_CONVEX_URL --cmd 'bun run build:web'",
				outputDirectory: "apps/web/dist",
			}),
		),
		file(
			"convex.json",
			toJson({
				authKit: {
					dev: {
						configure: {
							redirectUris: ["http://localhost:5173/callback"],
							appHomepageUrl: "http://localhost:5173",
							corsOrigins: ["http://localhost:5173"],
						},
						localEnvVars: {
							VITE_WORKOS_CLIENT_ID: "${authEnv.WORKOS_CLIENT_ID}",
							VITE_WORKOS_REDIRECT_URI: "http://localhost:5173/callback",
						},
					},
					preview: {
						configure: {
							redirectUris: ["https://${buildEnv.VERCEL_BRANCH_URL}/callback"],
							appHomepageUrl:
								"https://${buildEnv.VERCEL_PROJECT_PRODUCTION_URL}",
							corsOrigins: ["https://${buildEnv.VERCEL_BRANCH_URL}"],
						},
					},
					prod: {
						configure: {
							redirectUris: [
								"https://${buildEnv.VERCEL_PROJECT_PRODUCTION_URL}/callback",
							],
							appHomepageUrl:
								"https://${buildEnv.VERCEL_PROJECT_PRODUCTION_URL}",
							corsOrigins: [
								"https://${buildEnv.VERCEL_PROJECT_PRODUCTION_URL}",
							],
						},
					},
				},
			}),
		),
		file(
			"convex/auth.config.ts",
			`const clientId = process.env.WORKOS_CLIENT_ID;

const authConfig = {
	providers: [
		{
			type: "customJwt",
			issuer: "https://api.workos.com/",
			algorithm: "RS256",
			jwks: \`https://api.workos.com/sso/jwks/\${clientId}\`,
			applicationID: clientId,
		},
		{
			type: "customJwt",
			issuer: \`https://api.workos.com/user_management/\${clientId}\`,
			algorithm: "RS256",
			jwks: \`https://api.workos.com/sso/jwks/\${clientId}\`,
		},
	],
};

export default authConfig;
`,
		),
		file(
			"convex/schema.ts",
			`import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
	organizations: defineTable({
		name: v.string(),
		slug: v.string(),
		workosOrganizationId: v.optional(v.string()),
		billingStatus: v.union(
			v.literal("trial"),
			v.literal("active"),
			v.literal("past_due"),
			v.literal("canceled"),
		),
	}).index("by_slug", ["slug"]).index("by_workos_org", ["workosOrganizationId"]),
	memberships: defineTable({
		organizationId: v.id("organizations"),
		userId: v.string(),
		role: v.union(v.literal("owner"), v.literal("admin"), v.literal("member")),
	}).index("by_user", ["userId"]).index("by_organization", ["organizationId"]).index("by_user_organization", [
		"userId",
		"organizationId",
	]),
});
`,
		),
		file(
			"convex/organizations.ts",
			`import { ConvexError, v } from "convex/values";
import { mutation, query, type MutationCtx, type QueryCtx } from "./_generated/server";
import type { Id } from "./_generated/dataModel";

async function requireIdentity(ctx: QueryCtx | MutationCtx) {
	const identity = await ctx.auth.getUserIdentity();
	if (!identity) {
		throw new ConvexError("Authentication required.");
	}
	return identity;
}

export async function requireMembership(
	ctx: QueryCtx | MutationCtx,
	organizationId: Id<"organizations">,
) {
	const identity = await requireIdentity(ctx);
	const membership = await ctx.db
		.query("memberships")
		.withIndex("by_user_organization", (q) =>
			q.eq("userId", identity.subject).eq("organizationId", organizationId),
		)
		.unique();

	if (!membership) {
		throw new ConvexError("Organization membership required.");
	}

	return { identity, membership };
}

export const viewer = query({
	args: {},
	handler: async (ctx) => {
		const identity = await requireIdentity(ctx);
		return {
			subject: identity.subject,
			name: identity.name ?? null,
			email: identity.email ?? null,
		};
	},
});

export const listForCurrentUser = query({
	args: {},
	handler: async (ctx) => {
		const identity = await requireIdentity(ctx);
		const memberships = await ctx.db
			.query("memberships")
			.withIndex("by_user", (q) => q.eq("userId", identity.subject))
			.collect();

		const rows = [];
		for (const membership of memberships) {
			const organization = await ctx.db.get(membership.organizationId);
			if (organization) {
				rows.push({ organization, membership });
			}
		}

		return rows;
	},
});

export const create = mutation({
	args: {
		name: v.string(),
		slug: v.string(),
	},
	handler: async (ctx, args) => {
		const identity = await requireIdentity(ctx);
		const existing = await ctx.db
			.query("organizations")
			.withIndex("by_slug", (q) => q.eq("slug", args.slug))
			.unique();

		if (existing) {
			throw new ConvexError("Organization slug is already taken.");
		}

		const organizationId = await ctx.db.insert("organizations", {
			name: args.name,
			slug: args.slug,
			billingStatus: "trial",
		});

		await ctx.db.insert("memberships", {
			organizationId,
			userId: identity.subject,
			role: "owner",
		});

		return organizationId;
	},
});
`,
		),
		file(
			"convex/README.md",
			`# Convex Backend

Run \`bunx convex dev\` from the repository root before editing backend functions. Then run \`bunx convex ai-files install\` and read the generated guidelines.

This scaffold uses WorkOS AuthKit through Convex-managed configuration by default. Tenant checks belong in Convex helpers, not in client-only route guards.
`,
		),
		file(
			"packages/config/package.json",
			toJson({
				name: `${scope}/config`,
				private: true,
				version: "0.1.0",
				type: "module",
				exports: {
					"./tsconfig/base": "./tsconfig/base.json",
				},
			}),
		),
		file(
			"packages/config/tsconfig/base.json",
			toJson({
				compilerOptions: {
					target: "ES2022",
					useDefineForClassFields: true,
					lib: ["ES2022", "DOM", "DOM.Iterable"],
					allowJs: false,
					skipLibCheck: true,
					esModuleInterop: true,
					allowSyntheticDefaultImports: true,
					strict: true,
					forceConsistentCasingInFileNames: true,
					module: "ESNext",
					moduleResolution: "Bundler",
					resolveJsonModule: true,
					isolatedModules: true,
					noEmit: true,
					jsx: "react-jsx",
				},
			}),
		),
		file(
			"packages/ui/package.json",
			toJson({
				name: `${scope}/ui`,
				private: true,
				version: "0.1.0",
				type: "module",
				scripts: {
					build: "tsc --noEmit",
					check: "tsc --noEmit",
				},
				exports: {
					"./styles.css": "./src/styles.css",
					"./lib/utils": "./src/lib/utils.ts",
					"./components/ui/badge": "./src/components/ui/badge.tsx",
					"./components/ui/button": "./src/components/ui/button.tsx",
					"./components/ui/card": "./src/components/ui/card.tsx",
				},
				dependencies: {
					"class-variance-authority": pins.classVarianceAuthority,
					clsx: pins.clsx,
					"lucide-react": pins.lucideReact,
					"tailwind-merge": pins.tailwindMerge,
				},
				peerDependencies: {
					react: pins.react,
				},
				devDependencies: {
					"@types/react": pins.typesReact,
					typescript: pins.typescript,
				},
			}),
		),
		file(
			"packages/ui/tsconfig.json",
			toJson({
				extends: "../config/tsconfig/base.json",
				include: ["src"],
			}),
		),
		file(
			"packages/ui/src/lib/utils.ts",
			`import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}
`,
		),
		file(
			"packages/ui/src/components/ui/button.tsx",
			`import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/utils";

const buttonVariants = cva(
	"inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
	{
		variants: {
			variant: {
				default: "bg-primary text-primary-foreground hover:bg-primary/90",
				secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
				outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
				ghost: "hover:bg-accent hover:text-accent-foreground",
			},
			size: {
				default: "h-10 px-4 py-2",
				sm: "h-9 rounded-md px-3",
				lg: "h-11 rounded-md px-8",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	},
);

export interface ButtonProps
	extends React.ButtonHTMLAttributes<HTMLButtonElement>,
		VariantProps<typeof buttonVariants> {}

export function Button({ className, variant, size, ...props }: ButtonProps) {
	return <button className={cn(buttonVariants({ variant, size, className }))} {...props} />;
}

export { buttonVariants };
`,
		),
		file(
			"packages/ui/src/components/ui/card.tsx",
			`import * as React from "react";
import { cn } from "../../lib/utils";

export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
	return <div className={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)} {...props} />;
}

export function CardHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
	return <div className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />;
}

export function CardTitle({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) {
	return <h3 className={cn("text-lg font-semibold leading-none tracking-normal", className)} {...props} />;
}

export function CardDescription({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) {
	return <p className={cn("text-sm text-muted-foreground", className)} {...props} />;
}

export function CardContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
	return <div className={cn("p-6 pt-0", className)} {...props} />;
}
`,
		),
		file(
			"packages/ui/src/components/ui/badge.tsx",
			`import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "../../lib/utils";

const badgeVariants = cva(
	"inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors",
	{
		variants: {
			variant: {
				default: "border-transparent bg-primary text-primary-foreground",
				secondary: "border-transparent bg-secondary text-secondary-foreground",
				outline: "text-foreground",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	},
);

export interface BadgeProps
	extends React.HTMLAttributes<HTMLDivElement>,
		VariantProps<typeof badgeVariants> {}

export function Badge({ className, variant, ...props }: BadgeProps) {
	return <div className={cn(badgeVariants({ variant, className }))} {...props} />;
}
`,
		),
		file(
			"packages/ui/src/styles.css",
			`@theme inline {
	--color-background: var(--background);
	--color-foreground: var(--foreground);
	--color-card: var(--card);
	--color-card-foreground: var(--card-foreground);
	--color-primary: var(--primary);
	--color-primary-foreground: var(--primary-foreground);
	--color-secondary: var(--secondary);
	--color-secondary-foreground: var(--secondary-foreground);
	--color-muted: var(--muted);
	--color-muted-foreground: var(--muted-foreground);
	--color-accent: var(--accent);
	--color-accent-foreground: var(--accent-foreground);
	--color-border: var(--border);
	--color-input: var(--input);
	--color-ring: var(--ring);
	--radius: 0.5rem;
	--radius-sm: calc(var(--radius) * 0.75);
	--radius-md: calc(var(--radius) * 0.875);
	--radius-lg: var(--radius);
	--font-sans: "Geist", "Geist Fallback", ui-sans-serif, system-ui, sans-serif;
	--font-mono: "Geist Mono", "Geist Mono Fallback", ui-monospace, monospace;
}

:root {
	--background: oklch(0.985 0.004 95);
	--foreground: oklch(0.18 0.022 250);
	--card: oklch(1 0 0);
	--card-foreground: var(--foreground);
	--primary: oklch(0.49 0.13 220);
	--primary-foreground: oklch(0.98 0.005 240);
	--secondary: oklch(0.93 0.012 240);
	--secondary-foreground: oklch(0.22 0.025 250);
	--muted: oklch(0.93 0.012 240);
	--muted-foreground: oklch(0.48 0.027 250);
	--accent: oklch(0.91 0.04 190);
	--accent-foreground: oklch(0.22 0.04 240);
	--border: oklch(0.87 0.014 245);
	--input: var(--border);
	--ring: oklch(0.58 0.15 215);
}

.dark {
	--background: oklch(0.17 0.018 255);
	--foreground: oklch(0.96 0.006 240);
	--card: oklch(0.22 0.021 255);
	--card-foreground: var(--foreground);
	--primary: oklch(0.72 0.12 205);
	--primary-foreground: oklch(0.15 0.025 250);
	--secondary: oklch(0.29 0.027 255);
	--secondary-foreground: oklch(0.96 0.006 240);
	--muted: oklch(0.29 0.027 255);
	--muted-foreground: oklch(0.72 0.018 245);
	--accent: oklch(0.34 0.06 205);
	--accent-foreground: oklch(0.96 0.006 240);
	--border: oklch(0.35 0.027 255);
	--input: var(--border);
	--ring: oklch(0.72 0.12 205);
}

* {
	border-color: var(--border);
}

body {
	background: var(--background);
	color: var(--foreground);
	font-family: var(--font-sans);
}
`,
		),
		...webAppFiles(ctx),
		...marketingAppFiles(ctx),
		...microSaasDocs(ctx),
	];
}

function webAppFiles(ctx: CreateContext): GeneratedFile[] {
	const scope = ctx.packageScope;
	return [
		file(
			"apps/web/package.json",
			toJson({
				name: `${scope}/web`,
				private: true,
				version: "0.1.0",
				type: "module",
				scripts: {
					dev: "vite --host 0.0.0.0 --port 5173",
					build: "tsc --noEmit && vite build",
					check: "tsc --noEmit",
					preview: "vite preview --host 0.0.0.0 --port 4173",
				},
				dependencies: {
					[`${scope}/ui`]: "workspace:*",
					"@convex-dev/workos": pins.convexWorkos,
					"@workos-inc/authkit-react": pins.workosAuthKitReact,
					convex: pins.convex,
					"lucide-react": pins.lucideReact,
					react: pins.react,
					"react-dom": pins.reactDom,
				},
				devDependencies: {
					"@tailwindcss/vite": pins.tailwindcssVite,
					"@types/react": pins.typesReact,
					"@types/react-dom": pins.typesReactDom,
					"@vitejs/plugin-react": pins.viteReact,
					typescript: pins.typescript,
					vite: pins.vite,
				},
			}),
		),
		file(
			"apps/web/index.html",
			`<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>${ctx.projectName} App</title>
	</head>
	<body>
		<div id="root"></div>
		<script type="module" src="/src/main.tsx"></script>
	</body>
</html>
`,
		),
		file(
			"apps/web/tsconfig.json",
			toJson({
				extends: "../../packages/config/tsconfig/base.json",
				compilerOptions: {
					types: ["vite/client"],
					baseUrl: ".",
					paths: {
						"@/*": ["src/*"],
					},
				},
				include: ["src", "../../convex/**/*.ts"],
			}),
		),
		file(
			"apps/web/vite.config.ts",
			`import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vite";

export default defineConfig({
	plugins: [react(), tailwindcss()],
	resolve: {
		alias: {
			"@": fileURLToPath(new URL("./src", import.meta.url)),
		},
	},
	server: {
		port: 5173,
	},
});
`,
		),
		file(
			"apps/web/src/index.css",
			`@import "tailwindcss";
@source "../../../packages/ui/src/**/*.{ts,tsx}";
@import "${scope}/ui/styles.css";
`,
		),
		file(
			"apps/web/src/main.tsx",
			`import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { AuthKitProvider, useAuth } from "@workos-inc/authkit-react";
import { ConvexReactClient } from "convex/react";
import { ConvexProviderWithAuthKit } from "@convex-dev/workos";
import App from "./App";
import "./index.css";

document.documentElement.classList.add("dark");

function requiredEnv(name: string, value: string | undefined): string {
	if (!value) {
		throw new Error(\`Missing required environment variable: \${name}\`);
	}
	return value;
}

const convex = new ConvexReactClient(
	requiredEnv("VITE_CONVEX_URL", import.meta.env.VITE_CONVEX_URL),
);

createRoot(document.getElementById("root")!).render(
	<StrictMode>
		<AuthKitProvider
			clientId={requiredEnv("VITE_WORKOS_CLIENT_ID", import.meta.env.VITE_WORKOS_CLIENT_ID)}
			redirectUri={requiredEnv("VITE_WORKOS_REDIRECT_URI", import.meta.env.VITE_WORKOS_REDIRECT_URI)}
			devMode={import.meta.env.DEV}
		>
			<ConvexProviderWithAuthKit client={convex} useAuth={useAuth}>
				<App />
			</ConvexProviderWithAuthKit>
		</AuthKitProvider>
	</StrictMode>,
);
`,
		),
		file(
			"apps/web/src/App.tsx",
			`import { Authenticated, AuthLoading, Unauthenticated, useMutation, useQuery } from "convex/react";
import { useAuth } from "@workos-inc/authkit-react";
import { ArrowRight, Building2, CheckCircle2, LogOut, Settings } from "lucide-react";
import { api } from "../../../convex/_generated/api";
import { Badge } from "${scope}/ui/components/ui/badge";
import { Button } from "${scope}/ui/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "${scope}/ui/components/ui/card";

export default function App() {
	const { user, signIn, signOut } = useAuth();

	return (
		<main className="min-h-screen bg-background text-foreground">
			<header className="border-b bg-card/70 backdrop-blur">
				<div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
					<div>
						<p className="text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground">Micro-SaaS</p>
						<h1 className="text-xl font-semibold">${ctx.projectName}</h1>
					</div>
					<Button variant="outline" onClick={() => (user ? void signOut() : void signIn())}>
						{user ? <LogOut className="mr-2 h-4 w-4" /> : <ArrowRight className="mr-2 h-4 w-4" />}
						{user ? "Sign out" : "Sign in"}
					</Button>
				</div>
			</header>

			<AuthLoading>
				<section className="mx-auto max-w-6xl px-6 py-10">
					<Card>
						<CardHeader>
							<CardTitle>Loading workspace</CardTitle>
							<CardDescription>AuthKit and Convex are exchanging the session token.</CardDescription>
						</CardHeader>
					</Card>
				</section>
			</AuthLoading>

			<Unauthenticated>
				<section className="mx-auto grid max-w-6xl gap-6 px-6 py-10 lg:grid-cols-[1.1fr_0.9fr]">
					<div className="space-y-6">
						<Badge variant="secondary">WorkOS + Convex ready</Badge>
						<h2 className="max-w-2xl text-4xl font-semibold tracking-normal">Start from a tenant-aware product shell, not a blank demo.</h2>
						<p className="max-w-2xl text-muted-foreground">
							The scaffold includes authentication, organization membership, shared UI, Vercel deploy notes, and agent runbooks.
						</p>
						<Button size="lg" onClick={() => void signIn()}>
							Sign in to create a workspace
							<ArrowRight className="ml-2 h-4 w-4" />
						</Button>
					</div>
					<Card>
						<CardHeader>
							<CardTitle>Foundation included</CardTitle>
							<CardDescription>These seams are ready for your first paid workflow.</CardDescription>
						</CardHeader>
						<CardContent className="grid gap-3">
							{["Organization membership", "Billing shell", "Shared shadcn UI", "Agent-native docs"].map((item) => (
								<div className="flex items-center gap-3 rounded-md border bg-secondary/40 p-3" key={item}>
									<CheckCircle2 className="h-4 w-4 text-primary" />
									<span className="text-sm">{item}</span>
								</div>
							))}
						</CardContent>
					</Card>
				</section>
			</Unauthenticated>

			<Authenticated>
				<ProductDashboard />
			</Authenticated>
		</main>
	);
}

function ProductDashboard() {
	const viewer = useQuery(api.organizations.viewer);
	const organizations = useQuery(api.organizations.listForCurrentUser);
	const createOrganization = useMutation(api.organizations.create);

	return (
		<section className="mx-auto grid max-w-6xl gap-6 px-6 py-10">
			<div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
				<div>
					<Badge>Authenticated</Badge>
					<h2 className="mt-3 text-3xl font-semibold tracking-normal">Dashboard</h2>
					<p className="text-muted-foreground">Welcome {viewer?.name ?? viewer?.email ?? "operator"}.</p>
				</div>
				<Button
					onClick={() =>
						void createOrganization({
							name: "Acme Pilot",
							slug: "acme-pilot",
						})
					}
				>
					<Building2 className="mr-2 h-4 w-4" />
					Create demo org
				</Button>
			</div>

			<div className="grid gap-4 md:grid-cols-3">
				<Card>
					<CardHeader>
						<CardTitle>Organizations</CardTitle>
						<CardDescription>Tenant boundary for app data.</CardDescription>
					</CardHeader>
					<CardContent className="text-3xl font-semibold">{organizations?.length ?? "..."}</CardContent>
				</Card>
				<Card>
					<CardHeader>
						<CardTitle>Billing</CardTitle>
						<CardDescription>Shell only in v1.</CardDescription>
					</CardHeader>
					<CardContent><Badge variant="outline">Stripe-ready seam</Badge></CardContent>
				</Card>
				<Card>
					<CardHeader>
						<CardTitle>Settings</CardTitle>
						<CardDescription>Account and team controls.</CardDescription>
					</CardHeader>
					<CardContent><Settings className="h-6 w-6 text-muted-foreground" /></CardContent>
				</Card>
			</div>

			<Card>
				<CardHeader>
					<CardTitle>Your organizations</CardTitle>
					<CardDescription>Membership-aware queries live in Convex.</CardDescription>
				</CardHeader>
				<CardContent className="grid gap-3">
					{organizations?.length ? (
						organizations.map((row) => (
							<div className="flex items-center justify-between rounded-md border p-4" key={row.organization._id}>
								<div>
									<p className="font-medium">{row.organization.name}</p>
									<p className="text-sm text-muted-foreground">/{row.organization.slug}</p>
								</div>
								<Badge variant="secondary">{row.membership.role}</Badge>
							</div>
						))
					) : (
						<p className="text-sm text-muted-foreground">Create a demo organization to test the tenant shell.</p>
					)}
				</CardContent>
			</Card>
		</section>
	);
}
`,
		),
	];
}

function marketingAppFiles(ctx: CreateContext): GeneratedFile[] {
	const scope = ctx.packageScope;
	return [
		file(
			"apps/marketing/package.json",
			toJson({
				name: `${scope}/marketing`,
				private: true,
				version: "0.1.0",
				type: "module",
				scripts: {
					dev: "vite --host 0.0.0.0 --port 5174",
					build: "tsc --noEmit && vite build",
					check: "tsc --noEmit",
					preview: "vite preview --host 0.0.0.0 --port 4174",
				},
				dependencies: {
					[`${scope}/ui`]: "workspace:*",
					"lucide-react": pins.lucideReact,
					react: pins.react,
					"react-dom": pins.reactDom,
				},
				devDependencies: {
					"@tailwindcss/vite": pins.tailwindcssVite,
					"@types/react": pins.typesReact,
					"@types/react-dom": pins.typesReactDom,
					"@vitejs/plugin-react": pins.viteReact,
					typescript: pins.typescript,
					vite: pins.vite,
				},
			}),
		),
		file(
			"apps/marketing/index.html",
			`<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>${ctx.projectName}</title>
	</head>
	<body>
		<div id="root"></div>
		<script type="module" src="/src/main.tsx"></script>
	</body>
</html>
`,
		),
		file(
			"apps/marketing/tsconfig.json",
			toJson({
				extends: "../../packages/config/tsconfig/base.json",
				compilerOptions: {
					types: ["vite/client"],
					baseUrl: ".",
					paths: {
						"@/*": ["src/*"],
					},
				},
				include: ["src"],
			}),
		),
		file(
			"apps/marketing/vite.config.ts",
			`import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vite";

export default defineConfig({
	plugins: [react(), tailwindcss()],
	resolve: {
		alias: {
			"@": fileURLToPath(new URL("./src", import.meta.url)),
		},
	},
	server: {
		port: 5174,
	},
});
`,
		),
		file(
			"apps/marketing/src/index.css",
			`@import "tailwindcss";
@source "../../../packages/ui/src/**/*.{ts,tsx}";
@import "${scope}/ui/styles.css";
`,
		),
		file(
			"apps/marketing/src/main.tsx",
			`import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

createRoot(document.getElementById("root")!).render(
	<StrictMode>
		<App />
	</StrictMode>,
);
`,
		),
		file(
			"apps/marketing/src/App.tsx",
			`import { ArrowRight, CheckCircle2, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "${scope}/ui/components/ui/badge";
import { Button, buttonVariants } from "${scope}/ui/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "${scope}/ui/components/ui/card";

const appUrl = import.meta.env.VITE_APP_URL ?? "http://localhost:5173";

export default function App() {
	return (
		<main className="min-h-screen bg-background text-foreground">
			<section className="mx-auto grid max-w-6xl gap-10 px-6 py-16 lg:grid-cols-[1.1fr_0.9fr] lg:py-24">
				<div className="space-y-8">
					<Badge variant="outline">Micro-SaaS launch system</Badge>
					<div className="space-y-5">
						<h1 className="max-w-3xl text-5xl font-semibold tracking-normal">Launch the boring parts once. Spend your taste on the product.</h1>
						<p className="max-w-2xl text-lg text-muted-foreground">
							${ctx.projectName} ships with a product app, marketing site, shared UI, WorkOS auth, Convex data, and billing seams.
						</p>
					</div>
					<div className="flex flex-wrap gap-3">
						<a className={buttonVariants({ size: "lg" })} href={appUrl}>
							Open app
							<ArrowRight className="ml-2 h-4 w-4" />
						</a>
						<a className={buttonVariants({ size: "lg", variant: "outline" })} href="#pricing">
							View pricing
						</a>
					</div>
				</div>

				<Card className="self-start">
					<CardHeader>
						<CardTitle>Included foundation</CardTitle>
						<CardDescription>Generated as separate apps so marketing can evolve without touching the dashboard.</CardDescription>
					</CardHeader>
					<CardContent className="grid gap-4">
						{[
							["Product app", "Authenticated dashboard and tenant model"],
							["Marketing site", "Landing and pricing shells"],
							["Shared UI", "shadcn-style package for consistent surfaces"],
							["Agent docs", "Runbooks that guide future agents"],
						].map(([title, copy]) => (
							<div className="rounded-md border p-4" key={title}>
								<p className="font-medium">{title}</p>
								<p className="text-sm text-muted-foreground">{copy}</p>
							</div>
						))}
					</CardContent>
				</Card>
			</section>

			<section className="border-y bg-secondary/40">
				<div className="mx-auto grid max-w-6xl gap-4 px-6 py-10 md:grid-cols-3">
					{[
						{ icon: Sparkles, title: "Fast first slice", copy: "Start with a working app shell and data path." },
						{ icon: ShieldCheck, title: "Auth aware", copy: "WorkOS and Convex are already aligned." },
						{ icon: CheckCircle2, title: "Extensible", copy: "Mobile and billing can arrive as recipes." },
					].map(({ icon: Icon, title, copy }) => (
						<div className="flex gap-3" key={title}>
							<Icon className="mt-1 h-5 w-5 text-primary" />
							<div>
								<p className="font-medium">{title}</p>
								<p className="text-sm text-muted-foreground">{copy}</p>
							</div>
						</div>
					))}
				</div>
			</section>

			<section className="mx-auto max-w-6xl px-6 py-16" id="pricing">
				<div className="mb-8 max-w-2xl">
					<Badge>Pricing shell</Badge>
					<h2 className="mt-3 text-3xl font-semibold tracking-normal">Add real billing when the offer is real.</h2>
					<p className="mt-3 text-muted-foreground">The scaffold includes pricing structure and Stripe-ready seams, but no live payment integration in v1.</p>
				</div>
				<div className="grid gap-4 md:grid-cols-3">
					{["Starter", "Growth", "Scale"].map((plan, index) => (
						<Card key={plan}>
							<CardHeader>
								<CardTitle>{plan}</CardTitle>
								<CardDescription>{index === 0 ? "Validate the workflow." : index === 1 ? "Sell to small teams." : "Expand into operations."}</CardDescription>
							</CardHeader>
							<CardContent>
								<p className="mb-4 text-3xl font-semibold">{index === 0 ? "$19" : index === 1 ? "$79" : "Custom"}</p>
								<Button className="w-full" variant={index === 1 ? "default" : "outline"}>Join waitlist</Button>
							</CardContent>
						</Card>
					))}
				</div>
			</section>
		</main>
	);
}
`,
		),
	];
}

function microSaasDocs(ctx: CreateContext): GeneratedFile[] {
	return [
		file(
			"docs/architecture.md",
			`# Architecture

This workspace is intentionally split into product, marketing, shared UI, shared config, and Convex.

- \`apps/web\`: authenticated product app.
- \`apps/marketing\`: static marketing and pricing surfaces.
- \`packages/ui\`: source-owned shadcn-style components and tokens.
- \`packages/config\`: shared TypeScript and future toolchain config.
- \`convex\`: backend functions, schema, and auth configuration.

Convex owns tenant-sensitive authorization. Client routes can hide UI, but backend functions must enforce membership.
`,
		),
		file(
			"docs/feature-workflow.md",
			`# Feature Workflow

Use this loop for new product slices:

1. Add or update Convex schema and functions.
2. Add one product screen in \`apps/web\`.
3. Promote reusable components to \`packages/ui\` only after the second real use.
4. Update marketing copy only when the feature changes the public offer.
5. Run \`${ctx.packageManager} run check\`, \`${ctx.packageManager} run test\`, and a focused browser smoke test.
`,
		),
		file(
			"docs/deployment.md",
			`# Deployment

The default Vercel project targets the product app:

- Install command: \`bun install\`
- Build command: \`bunx convex deploy --cmd-url-env-var-name VITE_CONVEX_URL --cmd 'bun run build:web'\`
- Output directory: \`apps/web/dist\`

For marketing, create a second Vercel project from the same repository:

- Build command: \`bun run build:marketing\`
- Output directory: \`apps/marketing/dist\`

Convex preview and production deployments need separate deploy keys. Keep WorkOS preview and production redirect/CORS settings aligned with \`convex.json\`.
`,
		),
		file(
			"docs/env.md",
			`# Environment

Local app env:

\`\`\`bash
VITE_CONVEX_URL=
VITE_WORKOS_CLIENT_ID=
VITE_WORKOS_REDIRECT_URI=http://localhost:5173/callback
\`\`\`

Convex backend env:

\`\`\`bash
bunx convex env set WORKOS_CLIENT_ID <client-id>
bunx convex env set WORKOS_API_KEY <api-key>
\`\`\`

When using a Convex-managed WorkOS team, \`bunx convex dev\` can provision and sync the local AuthKit values.
`,
		),
	];
}

function viteSpaFiles(ctx: CreateContext): GeneratedFile[] {
	const pkg = ctx.projectSlug;
	return [
		rootReadme(ctx, `${ctx.projectName} Vite SPA`),
		agentInstructions({ ...ctx, auth: "none", billing: "none" }),
		commonGitignore(),
		file(
			"package.json",
			toJson({
				name: pkg,
				private: true,
				version: "0.1.0",
				type: "module",
				scripts: {
					dev: "vite --host 0.0.0.0 --port 5173",
					"dev:convex": "bunx convex dev",
					build: "tsc --noEmit && vite build",
					check: "tsc --noEmit && bunx convex typecheck",
					test: "vitest run",
					preview: "vite preview --host 0.0.0.0 --port 4173",
					"convex:deploy": "bunx convex deploy",
				},
				dependencies: {
					convex: pins.convex,
					react: pins.react,
					"react-dom": pins.reactDom,
					"class-variance-authority": pins.classVarianceAuthority,
					clsx: pins.clsx,
					"tailwind-merge": pins.tailwindMerge,
					"lucide-react": pins.lucideReact,
				},
				devDependencies: {
					"@tailwindcss/vite": pins.tailwindcssVite,
					"@types/react": pins.typesReact,
					"@types/react-dom": pins.typesReactDom,
					"@vitejs/plugin-react": pins.viteReact,
					tailwindcss: pins.tailwindcss,
					typescript: pins.typescript,
					vite: pins.vite,
					"vite-plus": pins.vitePlus,
					vitest: pins.vitest,
				},
			}),
		),
		file(
			"recipe.lock.json",
			toJson({
				...viteSpaRecipe.lock,
				options: {
					auth: ctx.auth,
					billing: ctx.billing,
					deploy: ctx.deploy,
					packageManager: ctx.packageManager,
					shape: ctx.shape,
				},
			}),
		),
		file(
			"index.html",
			`<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>${ctx.projectName}</title>
	</head>
	<body>
		<div id="root"></div>
		<script type="module" src="/src/main.tsx"></script>
	</body>
</html>
`,
		),
		file(
			"vite.config.ts",
			`import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vite";

export default defineConfig({
	plugins: [react(), tailwindcss()],
	resolve: {
		alias: {
			"@": fileURLToPath(new URL("./src", import.meta.url)),
		},
	},
	server: {
		port: 5173,
	},
});
`,
		),
		file(
			"tsconfig.json",
			toJson({
				compilerOptions: {
					target: "ES2022",
					useDefineForClassFields: true,
					lib: ["ES2022", "DOM", "DOM.Iterable"],
					allowJs: false,
					skipLibCheck: true,
					esModuleInterop: true,
					allowSyntheticDefaultImports: true,
					strict: true,
					forceConsistentCasingInFileNames: true,
					module: "ESNext",
					moduleResolution: "Bundler",
					resolveJsonModule: true,
					isolatedModules: true,
					noEmit: true,
					jsx: "react-jsx",
					types: ["vite/client"],
					baseUrl: ".",
					paths: {
						"@/*": ["src/*"],
					},
				},
				include: ["src", "convex"],
			}),
		),
		file("src/index.css", `@import "tailwindcss";`),
		file(
			"src/lib/utils.ts",
			`import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}
`,
		),
		file(
			"src/main.tsx",
			`import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { ConvexProvider, ConvexReactClient } from "convex/react";
import App from "./App";
import "./index.css";

function requiredEnv(name: string, value: string | undefined): string {
	if (!value) {
		throw new Error(\`Missing required environment variable: \${name}\`);
	}
	return value;
}

const convex = new ConvexReactClient(
	requiredEnv("VITE_CONVEX_URL", import.meta.env.VITE_CONVEX_URL),
);

createRoot(document.getElementById("root")!).render(
	<StrictMode>
		<ConvexProvider client={convex}>
			<App />
		</ConvexProvider>
	</StrictMode>,
);
`,
		),
		file(
			"src/App.tsx",
			`import { useMutation, useQuery } from "convex/react";
import { Plus } from "lucide-react";
import { api } from "../convex/_generated/api";

export default function App() {
	const notes = useQuery(api.notes.list);
	const addNote = useMutation(api.notes.add);

	return (
		<main className="min-h-screen bg-neutral-950 px-6 py-12 text-neutral-50">
			<section className="mx-auto max-w-3xl space-y-6">
				<div>
					<p className="text-sm uppercase tracking-[0.2em] text-cyan-300">Vite + Convex</p>
					<h1 className="mt-3 text-4xl font-semibold">${ctx.projectName}</h1>
					<p className="mt-3 text-neutral-400">A compact scaffold for quick experiments before they become a micro-SaaS workspace.</p>
				</div>
				<button
					className="inline-flex items-center rounded-md bg-cyan-300 px-4 py-2 text-sm font-medium text-neutral-950 hover:bg-cyan-200"
					onClick={() => void addNote({ body: "First Convex note" })}
				>
					<Plus className="mr-2 h-4 w-4" />
					Add note
				</button>
				<div className="grid gap-3">
					{notes?.length ? notes.map((note) => (
						<div className="rounded-md border border-neutral-800 bg-neutral-900 p-4" key={note._id}>
							{note.body}
						</div>
					)) : <p className="text-neutral-400">Run Convex and add a note.</p>}
				</div>
			</section>
		</main>
	);
}
`,
		),
		file(
			"convex/schema.ts",
			`import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
	notes: defineTable({
		body: v.string(),
	}),
});
`,
		),
		file(
			"convex/notes.ts",
			`import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

export const list = query({
	args: {},
	handler: async (ctx) => {
		return ctx.db.query("notes").order("desc").take(20);
	},
});

export const add = mutation({
	args: {
		body: v.string(),
	},
	handler: async (ctx, args) => {
		return ctx.db.insert("notes", {
			body: args.body,
		});
	},
});
`,
		),
	];
}

const microSaasRecipe: RecipeManifest = {
	id: "micro-saas",
	title: "Micro-SaaS Monorepo",
	description:
		"Vite product app, static marketing app, shared shadcn-style UI, Convex backend, WorkOS AuthKit, and Vercel-ready deployment.",
	defaults: {
		auth: "workos",
		billing: "shell",
		deploy: "vercel",
		packageManager: "bun",
		shape: "monorepo",
	},
	supported: {
		auth: ["workos"],
		billing: ["shell", "none"],
		deploy: ["vercel", "none"],
		packageManagers: ["bun"],
		shapes: ["monorepo"],
	},
	vitePlus: {
		templateName: "micro-saas",
		description: "Agent-native micro-SaaS monorepo",
		monorepo: true,
	},
	lock: lock("micro-saas", [
		"Default recipe for paid micro-SaaS products.",
		"WorkOS is configured through Convex-managed AuthKit when possible.",
		"Billing is intentionally a shell, not a live Stripe integration.",
	]),
		create(context) {
			return {
			files: microSaasFiles(context),
			nextSteps: [
				"cd " + context.projectName,
				"bun install",
				"bunx convex dev",
				"bunx convex ai-files install",
				"bun run dev",
			],
			verification: [
				"bun run check",
				"bun run test",
				"bun run build:web",
				"bun run build:marketing",
				],
			};
		},
		planSetup(context) {
			return buildSetupPlan("micro-saas", context);
		},
	};

const viteSpaRecipe: RecipeManifest = {
	id: "vite-spa-convex",
	title: "Vite SPA + Convex",
	description:
		"Small standalone Vite React app with Convex and a simple example feature.",
	defaults: {
		auth: "none",
		billing: "none",
		deploy: "none",
		packageManager: "bun",
		shape: "standalone",
	},
	supported: {
		auth: ["none"],
		billing: ["none"],
		deploy: ["none", "vercel"],
		packageManagers: ["bun"],
		shapes: ["standalone"],
	},
	vitePlus: {
		templateName: "vite-spa-convex",
		description: "Standalone Vite React SPA with Convex",
		monorepo: false,
	},
	lock: lock("vite-spa-convex", [
		"Experiment recipe for quick Vite + Convex starts.",
		"Auth and billing stay out of this recipe by default.",
	]),
		create(context) {
			return {
			files: viteSpaFiles(context),
			nextSteps: [
				"cd " + context.projectName,
				"bun install",
				"bunx convex dev",
				"bunx convex ai-files install",
				"bun run dev",
			],
				verification: ["bun run check", "bun run test", "bun run build"],
			};
		},
		planSetup(context) {
			return buildSetupPlan("vite-spa-convex", context);
		},
	};

export const recipes = [microSaasRecipe, viteSpaRecipe] as const;

export function getRecipe(recipeId: RecipeId): RecipeManifest {
	const recipe = recipes.find((candidate) => candidate.id === recipeId);
	if (!recipe) {
		throw new Error(`Unknown recipe: ${recipeId}`);
	}
	return recipe;
}

export function recipeIds(): RecipeId[] {
	return recipes.map((recipe) => recipe.id);
}
